# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.campaign_1 import Campaign1


class TestCampaign1(unittest.TestCase):
    """ Campaign1 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaign1(self):
        """
        Test Campaign1
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.campaign_1.Campaign1()
        pass


if __name__ == '__main__':
    unittest.main()
