# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ ContactsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.contacts_api.ContactsApi()

    def tearDown(self):
        pass

    def test_create_contact(self):
        """
        Test case for create_contact

        Add a contact to a campaign
        """
        pass

    def test_delete_contact(self):
        """
        Test case for delete_contact

        Delete contact
        """
        pass

    def test_fetch_contacts(self):
        """
        Test case for fetch_contacts

        Get contacts for a campaign
        """
        pass

    def test_fetch_custom_fields(self):
        """
        Test case for fetch_custom_fields

        Get custom fields
        """
        pass

    def test_fetch_specific_contact(self):
        """
        Test case for fetch_specific_contact

        Get a specific contact
        """
        pass

    def test_update_contact(self):
        """
        Test case for update_contact

        Update a contact
        """
        pass


if __name__ == '__main__':
    unittest.main()
