# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.address import Address


class TestAddress(unittest.TestCase):
    """ Address unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddress(self):
        """
        Test Address
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.address.Address()
        pass


if __name__ == '__main__':
    unittest.main()
