# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.campaigns_api import CampaignsApi


class TestCampaignsApi(unittest.TestCase):
    """ CampaignsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.campaigns_api.CampaignsApi()

    def tearDown(self):
        pass

    def test_create_campaign(self):
        """
        Test case for create_campaign

        Create a new campaign
        """
        pass

    def test_delete_campaign(self):
        """
        Test case for delete_campaign

        Delete a campaign
        """
        pass

    def test_fetch_campaign(self):
        """
        Test case for fetch_campaign

        Get a specific campaign
        """
        pass

    def test_fetch_campaigns(self):
        """
        Test case for fetch_campaigns

        Get all campaigns
        """
        pass

    def test_update_campaign(self):
        """
        Test case for update_campaign

        Update a campaign
        """
        pass


if __name__ == '__main__':
    unittest.main()
