# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_6 import InlineResponse2006


class TestInlineResponse2006(unittest.TestCase):
    """ InlineResponse2006 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006(self):
        """
        Test InlineResponse2006
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_6.InlineResponse2006()
        pass


if __name__ == '__main__':
    unittest.main()
