# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.oauth_authorized_applications_api import OauthAuthorizedApplicationsApi


class TestOauthAuthorizedApplicationsApi(unittest.TestCase):
    """ OauthAuthorizedApplicationsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.oauth_authorized_applications_api.OauthAuthorizedApplicationsApi()

    def tearDown(self):
        pass

    def test_fetch_oauth_authorized_applications(self):
        """
        Test case for fetch_oauth_authorized_applications

        
        """
        pass

    def test_revoke_oauth_authorized_application(self):
        """
        Test case for revoke_oauth_authorized_application

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
