# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.answers_api import AnswersApi


class TestAnswersApi(unittest.TestCase):
    """ AnswersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.answers_api.AnswersApi()

    def tearDown(self):
        pass

    def test_fetch_contact_answers(self):
        """
        Test case for fetch_contact_answers

        Get contact's answers
        """
        pass

    def test_fetch_question_answers(self):
        """
        Test case for fetch_question_answers

        Get question's answers
        """
        pass


if __name__ == '__main__':
    unittest.main()
