# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """ WebhooksApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.webhooks_api.WebhooksApi()

    def tearDown(self):
        pass

    def test_create_webhook(self):
        """
        Test case for create_webhook

        Create a new webhook
        """
        pass

    def test_delete_webhook(self):
        """
        Test case for delete_webhook

        Delete a webhook
        """
        pass

    def test_fetch_webhook(self):
        """
        Test case for fetch_webhook

        Get a specific webhook
        """
        pass

    def test_fetch_webhooks(self):
        """
        Test case for fetch_webhooks

        Get all webhooks
        """
        pass

    def test_update_webhook(self):
        """
        Test case for update_webhook

        Update a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
