# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.error_errors import ErrorErrors


class TestErrorErrors(unittest.TestCase):
    """ ErrorErrors unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorErrors(self):
        """
        Test ErrorErrors
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.error_errors.ErrorErrors()
        pass


if __name__ == '__main__':
    unittest.main()
