# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.address import Address
from .models.answer import Answer
from .models.call import Call
from .models.campaign import Campaign
from .models.campaign_1 import Campaign1
from .models.contact import Contact
from .models.contact_1 import Contact1
from .models.contact_answers import ContactAnswers
from .models.contact_attribute import ContactAttribute
from .models.error import Error
from .models.error_errors import ErrorErrors
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001
from .models.inline_response_200_10 import InlineResponse20010
from .models.inline_response_200_2 import InlineResponse2002
from .models.inline_response_200_3 import InlineResponse2003
from .models.inline_response_200_4 import InlineResponse2004
from .models.inline_response_200_5 import InlineResponse2005
from .models.inline_response_200_6 import InlineResponse2006
from .models.inline_response_200_7 import InlineResponse2007
from .models.inline_response_200_8 import InlineResponse2008
from .models.inline_response_200_9 import InlineResponse2009
from .models.keyvalue import Keyvalue
from .models.oauth_authorized_application import OauthAuthorizedApplication
from .models.question import Question
from .models.webhook import Webhook
from .models.webhook_1 import Webhook1

# import apis into sdk package
from .apis.answers_api import AnswersApi
from .apis.calls_api import CallsApi
from .apis.campaigns_api import CampaignsApi
from .apis.contacts_api import ContactsApi
from .apis.custom_fields_api import CustomFieldsApi
from .apis.oauth_authorized_applications_api import OauthAuthorizedApplicationsApi
from .apis.questions_api import QuestionsApi
from .apis.webhooks_api import WebhooksApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
