# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .address import Address
from .answer import Answer
from .call import Call
from .campaign import Campaign
from .campaign_1 import Campaign1
from .contact import Contact
from .contact_1 import Contact1
from .contact_answers import ContactAnswers
from .contact_attribute import ContactAttribute
from .error import Error
from .error_errors import ErrorErrors
from .inline_response_200 import InlineResponse200
from .inline_response_200_1 import InlineResponse2001
from .inline_response_200_10 import InlineResponse20010
from .inline_response_200_2 import InlineResponse2002
from .inline_response_200_3 import InlineResponse2003
from .inline_response_200_4 import InlineResponse2004
from .inline_response_200_5 import InlineResponse2005
from .inline_response_200_6 import InlineResponse2006
from .inline_response_200_7 import InlineResponse2007
from .inline_response_200_8 import InlineResponse2008
from .inline_response_200_9 import InlineResponse2009
from .keyvalue import Keyvalue
from .oauth_authorized_application import OauthAuthorizedApplication
from .question import Question
from .webhook import Webhook
from .webhook_1 import Webhook1
