# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2009(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authorized_applications': 'list[OauthAuthorizedApplication]'
    }

    attribute_map = {
        'authorized_applications': 'authorized_applications'
    }

    def __init__(self, authorized_applications=None):
        """
        InlineResponse2009 - a model defined in Swagger
        """

        self._authorized_applications = None

        if authorized_applications is not None:
          self.authorized_applications = authorized_applications

    @property
    def authorized_applications(self):
        """
        Gets the authorized_applications of this InlineResponse2009.

        :return: The authorized_applications of this InlineResponse2009.
        :rtype: list[OauthAuthorizedApplication]
        """
        return self._authorized_applications

    @authorized_applications.setter
    def authorized_applications(self, authorized_applications):
        """
        Sets the authorized_applications of this InlineResponse2009.

        :param authorized_applications: The authorized_applications of this InlineResponse2009.
        :type: list[OauthAuthorizedApplication]
        """

        self._authorized_applications = authorized_applications

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2009):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
