# coding: utf-8

"""
    Upcall API

    A RESTful API (json) to manage your human-powered outbound call campaigns.

    OpenAPI spec version: 2
    Contact: support@upcall.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Keyvalue(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'key': 'str',
        'value': 'str'
    }

    attribute_map = {
        'id': 'id',
        'key': 'key',
        'value': 'value'
    }

    def __init__(self, id=None, key=None, value=None):
        """
        Keyvalue - a model defined in Swagger
        """

        self._id = None
        self._key = None
        self._value = None

        if id is not None:
          self.id = id
        if key is not None:
          self.key = key
        self.value = value

    @property
    def id(self):
        """
        Gets the id of this Keyvalue.

        :return: The id of this Keyvalue.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Keyvalue.

        :param id: The id of this Keyvalue.
        :type: str
        """

        self._id = id

    @property
    def key(self):
        """
        Gets the key of this Keyvalue.
        The key to reference a value

        :return: The key of this Keyvalue.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this Keyvalue.
        The key to reference a value

        :param key: The key of this Keyvalue.
        :type: str
        """

        self._key = key

    @property
    def value(self):
        """
        Gets the value of this Keyvalue.
        The vallue associated to a key

        :return: The value of this Keyvalue.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this Keyvalue.
        The vallue associated to a key

        :param value: The value of this Keyvalue.
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Keyvalue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
